### PR TITLE
Acknowledgements title

### PR DESCRIPTION
**Pull request by dabodamjan**
Creates AcknowledgementDetailsView.
Adds title to AcknowledgementDetailsView.
Adds optional title for AcknowledgementsList.

### CODE REVIEW

**Comment by JulesMoorhouse** [comment]
👍

**Comment by JulesMoorhouse** [comment]
I think the version number of the package will need to changed.

**Review by MartinP7r — APPROVED** [review]
LGTM 👍🏼  

Thank you for your contribution! 🙇🏼

**Comment by dabodamjan** [comment]
It says "Only those with write access to this repository can merge pull requests."
Can you merge it? @MartinP7r

**Comment by MartinP7r** [comment]
- @dabodamjan sorry I was already asleep by that time. 😅

**Pull request merged**
